### ISSUE TITLE
#define BOOLFORKEY @"dhGuidePage"

### ISSUE THREAD

**Issue by myGitHubHehe** [dingding3w/DHGuidePageHUD#10]
请问这个宏只是演示的时候用的吗？

**Comment by dingding3w** [comment]
#define BOOLFORKEY @"dhGuidePage"  可根据实际要求自行修改， 具体作用请阅读：https://github.com/dingding3w/DHGuidePageHUD/blob/master/README.md#%E5%8F%AF%E8%83%BD%E4%BC%9A%E7%94%A8%E5%88%B0%E7%9A%84%E4%BB%A3%E7%A0%81%E8%AF%B4%E6%98%8E

**Comment by myGitHubHehe** [comment]
好的
